stages:
  – build
  – deploy

image: alpine

before_script:
  – git config –global http.sslVerify false

get_packer:
  stage: build
  artifacts:
    paths:
    – packer
  script:
    – echo "Fetching packer"
    – wget https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip
    – unzip packer_1.8.0_linux_amd64.zip
    – chmod +x packer
